In [1]:
import numpy as np

In [2]:
# For 2D Array

arr2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)

print(np.sum(arr2D))            # Sum of every element in the array

sum_of_columns=np.sum(arr2D,axis=0)      # Sum of Columns will be done only with the help of axis=0
print(sum_of_columns)

sum_of_rows=np.sum(arr2D,axis=1)      # Sum of Rows will be done only with the help of axis=1
print(sum_of_rows)

print(arr2D[0:2,1:2])                 # Slicing in 2D Array

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [3]:
# For 3D Array

arr3D=np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])         # 2*3*2
print(arr3D)

# Indexing
print(arr3D[0,1,1])

# Slicing
print(arr3D[:,0,:])          # It slices First row from both the layers
arr3D[:,0,:]=99
print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
4
[[1 2]
 [7 8]]
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]
