In [1]:
import numpy as np

In [2]:
# Integers

arr=np.array([1,2,3,4,5])
print(arr,arr.dtype)

[1 2 3 4 5] int64


In [5]:
# Floating Point Nums

arr1=np.array([1,2,3,4,5.12])
print(arr1,arr1.dtype)

arr2=np.array([1.3,2.4,3.5,4.12,5.12])
print(arr2,arr2.dtype)

[1.   2.   3.   4.   5.12] float64
[1.3  2.4  3.5  4.12 5.12] float64


In [7]:
# String 

arr1=np.array([1,2,3,4,5,"Ayush"])
print(arr1,arr1.dtype)

arr2=np.array(["Hii","I","am","Ayush","Gautam"])
print(arr2,arr2.dtype)

['1' '2' '3' '4' '5' 'Ayush'] <U21
['Hii' 'I' 'am' 'Ayush' 'Gautam'] <U6


In [10]:
# Complex Nums

arr=np.array([2 + 5j])
print(arr,arr.dtype)

[2.+5.j] complex128


In [ ]:
# Object Data Type

arr=np.array(["Ayush",3,{1,2,5,6}])
print(arr,arr.dtype)