In [1]:
import numpy as np 

In [2]:
# Operations On Numpy-Arrays

# 1-> Reshaping an Array (It is only possible when we have compatible number of elements there should be equal number of elements in both the arrays.)

arr=np.array([[1,2,3],[4,5,6]])      # Dimension -> (2,3)
print(arr,arr.shape)

reshaped_arr=arr.reshape((3,2))      # Reshaping the array to Dimension -> (3,2)
print(reshaped_arr,reshaped_arr.shape)

flattened_arr=arr.flatten()          # It changes number of Dimension of an array from 2D,3D,4D,.....nD -> 1D
print(flattened_arr,flattened_arr.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)
