In [1]:
import numpy as np

In [3]:
# In Python List

py_list=[1,2,3,4,5]
print([i*i for i in py_list])
print([i+5 for i in py_list])

# Vectorization In Numpy-Arrays

arr=np.array([1,2,3,4,5])
print(arr**2)
print(arr+5)

[1, 4, 9, 16, 25]
[6, 7, 8, 9, 10]
[ 1  4  9 16 25]
[ 6  7  8  9 10]


In [4]:
# Broadcating

arr1=np.array([1,2,3,4,5])
print(arr+5)  # Here Broadcasting is performed in Background

arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr1+arr2)


[ 6  7  8  9 10]
[[ 2  4  6  8 10]
 [ 7  9 11 13 15]]
