In [1]:
import numpy as np

In [5]:
# Create from Lists

arr=np.array([1,2,3,4,5,6])
print(arr,type(arr),arr.dtype,arr.shape)

[12  3  4  5  6] <class 'numpy.ndarray'> int64


In [4]:
# Create from Lists but with string also there in list

arr=np.array([1,2,3,4,5,6,"Ayush"])
print(arr,type(arr),arr.dtype,arr.shape)   # Every thing inside array will be converted to string 

['12' '3' '4' '5' '6' 'Ayush'] <U21


In [6]:
# Create from 2-D Lists 

list=[[1,2,3],[4,5,6],[7,8,9]]
arr2D=np.array(list)
print(arr2D,type(arr2D),arr2D.dtype,arr2D.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'> int64 (3, 3)
